### ISSUE TITLE
wildcards

### ISSUE THREAD

**Issue by yamtssfa** [raquo/hnapp#10]
Wildcards don't seem to work. For example I want -ukrai* in my search. Thanks

**Comment by raquo** [comment]
Sorry, wildcards are not supported, and I have no plans to implement them.

hnapp supports basic stemming, e.g. if you search for "sponsored" you'll get words like "sponsor" as well, but it doesn't cover _all_ variations of the same word root. You'll need to specify all the word variations that you want to exclude from your query.
